# Generated by Django 6.0.6 on 2026-07-03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_article_and_articleinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
    ]
